name: Run RAP BO API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Inso CLI
        run: npm install -g inso

      - name: Run Insomnia Tests
        run: inso run test ./RAP_Customer_BO_API_test_scenario_Insomnia_2025-05-21.yml
